name: donasitrack_mobile
description: DonasiTrack mobile application
publish_to: none
version: 0.0.1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.7+4
  geolocator: ^14.0.2
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
